Refactoring language chart data
9XDM/YOP pull request #14
Opened 2017-01-25 16:17 UTC by originerd

간단한 리팩토링을 진행했습니다.
- language-chart-data.js
  - 오타 수정
  - 프로그래밍 언어를 찾는 정규식 동적으로 생성
  - 프로그래밍 언어 갯수 세는 로직 간소화
  - TypeScript 및 Elixir 프로그래밍 언어 목록에 추가

간단하게 테스트하면서 진행했습니다. 리뷰 부탁드려요 😁

2017-01-26 00:19 UTC, myungseokang approved these changes

2017-01-26 03:35 UTC, qkraudghgh requested changes
LGTM!
기여 너무 감사합니다.
급하게 짜느라 하드코딩 된 곳이 많았는데 많이 좋아졌네요
다만 로컬에서 돌려보니 오류나는 곳이 있어 코멘트 달았습니다.
확인해보시고 comment 부탁드립니다!

2017-01-26 03:35 UTC, qkraudghgh commented on language-chart-data.js
> +    'g',
'g'뒤에 `,`는 오타인건가요? 제 로컬에서 돌려보니 이거때문에 오류가 나서요
노드 v7.2.0를 쓰고있습니다. 혹시 오타라면 고치고 PR해주세요!

2017-01-26 03:58 UTC, originerd commented on language-chart-data.js
> +    'g',
아, 최근 JavaScript style guide에 맞게 작성했는데, 여러 줄일 경우 마지막 인자 뒤에도 `,`를 붙이는 방식으로 많이 쓰고 있어요. 근데, 노드에서는 제대로 지원되지 않네요... 반영해서 push 하겠습니다.

2017-01-27 11:32 UTC, qkraudghgh approved these changes

2017-01-27 11:32 UTC, merged